"""core.tilemap —— 瓦片地图模式核心（第 5 种模式）。

模块：
- prompts.py   瓦片集严格提示词（3×3 基础 / 2×2 地块生态图 / 2×2 建筑图）
- tiles.py     3×3 自适应裁切、2×2 块图裁切、九宫格/生态/建筑数据结构
- cleanup.py   底图清理：抹除每格深色线框、检测/修补文字水印
- seamless.py  无缝化：偏移错位缝合、纹理提取（九格中位数）、条带/描边实测、对齐化
- autotile.py  47-tile 生成（对齐式构图：AI 纹理 + 程序化几何）、双网格、多地形掩码
- buildings.py 建筑类：抠白底、墙体无缝、透明拼件（直段/端头/转角/立柱）
- map.py       瓦片地图数据模型（多地形 + 建筑 overlay）与渲染、序列化
"""
from .tiles import (
    BASE_POS_CHOICES,
    BLOCK_POSITIONS,
    BaseTileSet,
    BuildingSheet,
    EcosystemSheet,
    block_base_score,
    building_from_blocks,
    crop_base_3x3,
    crop_blocks,
    detect_base_block,
    ecosystem_from_blocks,
    normalize_tileset,
)
from .seamless import (
    align_terrain_set,
    make_axis_seamless,
    make_edge_seamless,
    make_texture_seamless,
    make_tile_texture,
    measure_terrain_art,
    median_tile_texture,
    prepare_terrain_set,
    process_base_set,
)
from .cleanup import (
    clean_centre_tile,
    detect_text_marks,
    patch_marks,
    strip_grid_frames,
)
from .autotile import (
    BIT,
    build_47_sheet,
    build_47_sheet_art,
    build_dual_pieces_sheet_art,
    canonical_mask,
    canonical_masks,
    compose_art_tile,
    compose_tile,
    derive_corners,
    mask_for_terrain,
    mask_from_neighbors,
    nearest_mask,
)
from .buildings import PIECE_NAMES, opaque_ratio, process_building_sheet
from .walls import (
    EXTRA_SLOTS,
    SOLID_SLOT,
    W16,
    W16_SLOTS,
    WallArt,
    build_piece_set as build_wall_pieces,
    build_wall_atlas,
    compose_wall_piece,
    mask16,
    rotate_piece,
    slot_for_mask,
    wall16_index,
    wall_art_from_sheet,
)
from .blob47 import (
    BLOB_TILE_COLS,
    BLOB_TILE_ROWS,
    FALLBACK_TILE_INDEX,
    FORBIDDEN_TILE_INDEX,
    MASK_TO_INDEX,
    ProceduralTerrain,
    atlas_cell_box,
    atlas_cell_size,
    blob_mask_to_slot_table,
    build_blob47_atlas,
    build_tile16_atlas,
    canonical_tile16_mask,
    compute_blob_mask,
    nearest_tile_index,
    slice_atlas_tile,
    tile16_index,
)
from .map import TileMapModel
from .prompts import (
    build_building_prompts,
    build_ecosystem_prompts,
    build_tileset_prompts,
)

__all__ = [
    "BaseTileSet",
    "EcosystemSheet",
    "BuildingSheet",
    "crop_base_3x3",
    "crop_blocks",
    "ecosystem_from_blocks",
    "building_from_blocks",
    "normalize_tileset",
    "BASE_POS_CHOICES",
    "BLOCK_POSITIONS",
    "block_base_score",
    "detect_base_block",
    "make_texture_seamless",
    "make_axis_seamless",
    "make_edge_seamless",
    "make_tile_texture",
    "median_tile_texture",
    "measure_terrain_art",
    "align_terrain_set",
    "prepare_terrain_set",
    "process_base_set",
    "strip_grid_frames",
    "detect_text_marks",
    "patch_marks",
    "clean_centre_tile",
    "BIT",
    "canonical_mask",
    "canonical_masks",
    "nearest_mask",
    "compose_tile",
    "compose_art_tile",
    "build_47_sheet",
    "build_47_sheet_art",
    "build_dual_pieces_sheet_art",
    "derive_corners",
    "mask_for_terrain",
    "mask_from_neighbors",
    "PIECE_NAMES",
    "opaque_ratio",
    "WallArt",
    "W16",
    "W16_SLOTS",
    "EXTRA_SLOTS",
    "SOLID_SLOT",
    "mask16",
    "wall16_index",
    "slot_for_mask",
    "compose_wall_piece",
    "build_wall_pieces",
    "build_wall_atlas",
    "wall_art_from_sheet",
    "MASK_TO_INDEX",
    "FORBIDDEN_TILE_INDEX",
    "FALLBACK_TILE_INDEX",
    "BLOB_TILE_COLS",
    "BLOB_TILE_ROWS",
    "compute_blob_mask",
    "nearest_tile_index",
    "blob_mask_to_slot_table",
    "atlas_cell_size",
    "atlas_cell_box",
    "slice_atlas_tile",
    "build_blob47_atlas",
    "build_tile16_atlas",
    "tile16_index",
    "canonical_tile16_mask",
    "ProceduralTerrain",
    "process_building_sheet",
    "rotate_piece",
    "TileMapModel",
    "build_tileset_prompts",
    "build_ecosystem_prompts",
    "build_building_prompts",
]
